name: parcels_v3_10yr_event
channels:
  - conda-forge
dependencies:
  - parcels >3.1.0
  - copernicusmarine >= 2

  # Kernel workshop dependencies
  - plotly

  # Visualization workshop dependencies
  - h5py
  - matplotlib
  - cartopy
  - cmocean
